version: '0.1'

services:
  mysqlDB:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root@password
      MYSQL_DATABASE: blogdb
      MYSQL_USER: joyboy
      MYSQL_PASSWORD: password
    ports:
      - "3306:3366"
    volumes:
      - blog_data:/var/lib/mysql

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/blogApp
    ports:
      - "8000:8000"
    depends_on:
      - mysqlDB


volumes:
  blog_data:
